databases:
  - name: bookeasy-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: bookeasy-api
    runtime: node
    region: frankfurt
    plan: free
    rootDir: apps/api
    buildCommand: cd ../.. && npm install && npm run build -w packages/shared && cd apps/api && npm run build
    startCommand: npx prisma migrate deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookeasy-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONT_URL
        sync: false

  - type: web
    name: bookeasy-web
    runtime: node
    region: frankfurt
    plan: free
    rootDir: apps/web
    buildCommand: cd ../.. && npm install && npm run build -w packages/shared && cd apps/web && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
